### ISSUE TITLE
v3 Problem with nested quotations

### ISSUE THREAD

**Issue by nowzig** [Angular-Dynamic-Hooks/ngx-dynamic-hooks#43]
While testing the new v3 of this library, excellent work by the way, we encountered a problem regarding the nesting of quotations.

For example
`<ngx-dynamic-hooks [content]="'<app-yform [content]="'<p class="text-warning">Test</p>'"></app-yform>'"></ngx-dynamic-hooks>`
does not work, because the double quotation is not escaped, but when escaping them e.g. like that
`<ngx-dynamic-hooks [content]="'<app-yform [content]=\"\'<p class=\"text-warning\">Test</p>\'\"></app-yform>'"></ngx-dynamic-hooks>`
we still get 
`Error: Input parse error. String was opened, but not closed.`

It seems that escaping is not correctly recognized.

**Comment by MTobisch** [comment]
Hey there!

thank you liking the library and trying out v3!

I've had a look at the issue and I think its mostly caused by how v3 of the library now primarily uses HTML-based parsing rather than Regex-based parsing and by how escaping works - or doesn't work - in HTML. 

Most importantly, you cannot use backslashes to escape chars in standard HTML like in JS/TS. It works in Angular []-input attributes to a degree, but even Angular doesn't allow escaping the same kind of quotes used to define the input attribute in the first place (double quotes, for example). For me, it throws compile time errors immediately. I'm not sure why it seemingly doesn't in your case. 

So in your example, trying to render

```html
<app-yform [content]=\"\'<p class=\"text-warning\">Test</p>\'\"></app-yform>
```

is rendered internally by the HTML parser all jumbled like:

```html
<app-yform [content]="'<p class=\" text-warning\"="">Test<p></p>'"&gt;</app-yform>
```

Then tries to make sense of the `content` input which is `'<p class=\` here and naturally gives the error `String was opened, but not closed.` because there's just one single quote at the beginning.

## Some solutions

### 1. Move the content into a TS file

You could just write it like this:

```ts
let content = `<app-yform [content]="'<p class='text-warning'>Test</p>'"></app-yform>`;
```

You could, but don't need to escape the inner single quote in this example because the library recognizes that the value of [content] is a string immediately as its value starts/ends with quotes and just passes it on blindly. 

The important part is never to reuse the same quotes used to define an input attribute in its value as that will trip HTML parsers up every time.

### 2. Use the context object

An even cleaner way to pass inputs is the use the context object.

```ts
let context = {
  notice: '<p class="text-warning">Test</p>'
};
let content = `<app-yform [content]="context.notice"></app-yform>`; 
```

```html
<ngx-dynamic-hooks [context]="context" [content]="content"></ngx-dynamic-hooks>
````

Now you just pass `context.notice` to the content input of YFormComponent and what is contained in that variable is never rendered directly in HTML at all. So you can use whatever characters you want, really.

### 3. Reenable regex-based parsing

As a last resort, if it worked fine in v2, but doesn't anymore in v3 even though you changed nothing about the code, you might be able to get it working again by manually returning to the old regex-based logic. Note that this needs **v3.0.1** of the library for the `parseWithRegex` option.

```ts
parsers: HookParserEntry[] = [{
  component: YFormComponent, // Adjust name as needed
  parseWithRegex: true       // This is the important part
}];
```

This would work with a content string like:

```ts
let content = `<app-yform [content]="'<p class=\\"text-warning\\">Test</p>'"></app-yform>`;
```

**Comment by nowzig** [comment]
Thank you very much for this very detailed answer.

I went for the 3rd solution as it worked in v2 and it works now in v3 as well.

Thank you again for that very quick help!
