### ISSUE TITLE
Text content in HTML parser

### ISSUE THREAD

**Issue by ManuelKuehne** [Angular-Dynamic-Hooks/ngx-dynamic-hooks#47]
First of all thank you for your work on this great project, I've been using it for some years already, especially your ready to use example of the link parser.

I now found some bug in my application using the RegEx parser for HTML elements (I know) and with upgrading to V3 I hoped to replace it with the superior HTML parser. My task is quite simple, I want to take the text content of a span and use it as an input for a component.

So from
`<span class='myClass'>Example Content</span>`
I want to use the directive
`<span [appMyDirective]='Example Content'></span>`

Unfortunately with the HTML Hook it seems like I can't access the text content of the original span via elementSnapshot in any way or did I miss something?
I found a solution for my regex with negative look ahead but the uglyness lead to me still asking if this problem is solvable via the HTML parser.
`<span class="myClass">(((?!<\/span).)*)` 

Thanks,
Manuel

**Comment by MTobisch** [comment]
Hey there!

Thank you for the kind words, first of all!

It seems you've indeed uncovered a shortcoming with the previous implementation of `elementSnapshot`. 

The library internally used the shallow version of [cloneNode](https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode) to create the snapshot. Even though it says that the clone contains all attributes and properties of the original element, it turns out that some primitive properties like `innerHTML` are in fact not copied over, probably to keep them in sync with other reference properties like `childNodes` (of which the shallow snapshot has none).

I've modified `elementSnapshot` to now contain a deep clone of the originally found element, hopefully providing more information. You can test it out in **v3.1.1** of the library.

### Your example

If I'm understanding it correctly, I'm assuming you wish to find spans like `<span class='myClass'>Example Content</span>`, then load a component that takes, let's say, `spanContent` as an input and internally renders `<span [appMyDirective]='spanContent'></span>`? 

A custom HookParser like this should then work with the new version:

```ts
class MyCustomParser implements HookParser {

  findHookElements(contentElement: any, context: any, options: ParseOptions): any[] {
    const selector = 'span.myClass';
    return Array.from((contentElement as HTMLElement).querySelectorAll(selector));
  }

  loadComponent(hookId: number, hookValue: HookValue, context: any, childNodes: any[], options: ParseOptions): HookComponentData {
    return {
      component: MyDynamicComponent
    }
  }

  getBindings(hookId: number, hookValue: HookValue, context: any, options: ParseOptions): HookBindings {
    return {
      inputs: {
        spanContent: hookValue.elementSnapshot.innerHTML
      },
      outputs: {}
    }
  }
}
```

**Comment by ManuelKuehne** [comment]
Thank you for that ultrafast reply. Yes, that is what my HookParser looked like and is now looking again. Works like a charm, thanks again! :D
